image: openjdk:8u141-jdk

pipelines:
  default:
    - step:
        script:
          - ./gradlew dependencies
          - ./gradlew check cobertura install --scan
          - ./gradlew -p acceptance-test test --scan
